### ISSUE TITLE
How to tell if Unpackerr can actually read the download folder

### ISSUE THREAD

**Issue by hysel** [Unpackerr/unpackerr#258]
Hi

I am evaluating whether I can use Unpackerr to monitor my download folder to qbittorrent without installing any Sonnar etc. My solution is running as a docker inside a TrueNAS server.

I have configured the UN_FOLDER_0_PATH option to my main download folder, but I can't even tell whether or not the mount option was successful, or I see Unpackerr going deep into the folder structure to unzip some files I put there on purpose. 

Is there a way to either shell or run remote command to list the content of the mounted folder?

Thanks in advance

Hysel

**Comment by davidnewhall** [comment]
Hello!

Unpackerr is available as a linux binary. Might be easier to test with that. The golift container has no shell, but the hotio container is based on alpine and has a shell. The containers are mostly interchangeable. 

Unpackerr watches for new folders appearing in the watch folder. It will not extract things that already exist when you start it, and it will not extract archives that are not in a folder.
Once you start it, rename a folder in your watch folder, and it should 'see' it. 

I'll also note that Unpackerr uses fsnotify (aka inotify) to watch the file system. When it detects it's running in Docker, it also starts a file system poller, but the poller only goes 1 folder deep. The poller exists because Docker generally doesn't pass fsnotify events through to containers. All that means that Unpackerr may start extracting your items before they finish downloading, when it runs from Docker.

If you'd like more detailed instructions making it work, please share your docker run command and unpackerr config (file/env vars).

**Comment by hysel** [comment]
Thank you very much for the quick reply. I understand better the solution.

Unfortunately, I do need a deep folder scanner that can extract files when it finds them.

Hysel
