### ISSUE TITLE
Allow use of ACL instead of chmod

### ISSUE THREAD

**Issue by TheXRMonk** [Unpackerr/unpackerr#269]
When using unpackerr on Truenas Scale on a dataset that's shared over SMB, "chmod" commands are not allowed, which fails the extraction.
I guess the permission are already set correctly by the umask so don't know why chmod is needed in the process, so maybe step one would be a config setting to skip the chmod command (or continue if it fails)?
Alternatively we should be able to use ACL commands instead of chmod.

Sources;
https://www.truenas.com/community/threads/smb-permissions-wont-allow-chmod-is-there-a-work-around.98387/
https://www.reddit.com/r/truenas/comments/vz86mb/cant_change_file_permissions_eg_chmod_a_file/

**Comment by davidnewhall** [comment]
Hello,

Everyone that has reported ZFS `chmod: invalid operation` has set ACLs to passthrough to get around this. 

I'll leave this issue open to remind me to put an `if` statement on the chmod. This will allow you to pass in a specific file or dir modes to prevent chmod.

**Comment by enticedwanderer** [comment]
I'm also impacted by this, and setting the ACLs to passthrough is not really a practical workaround since it actually resets away ACLs on files/folders after chmod... This can have wide ramifications elsewhere (on the share). Would love to see this become a innocuous warning rather than an error that interrupts the workflow, but it may not be as simple as an if statement since it's the [xtractr that has this behavior](https://github.com/golift/xtractr/blob/f06b575adde7e7969d303945b4be51f96c15c24f/files.go#L286-L290).

**Comment by davidnewhall** [comment]
Chmod has been removed in the unstable build https://unstable.golift.io
Docker tag `:unstable` will build tomorrow hopefully. Docker builds are currently broken because GitHub changed their SSH key.

This change will roll into the next release.
