### ISSUE TITLE
Support for direct qBittorrent integration 

### ISSUE THREAD

**Issue by 0xW1sKy** [Unpackerr/unpackerr#276]
Would like to request an integration directly with qBittorrent. 

Use Case: torrent files uploaded (usually season packs) that are not supported by the starr apps. 

These would then be unpacked with unpackerr to allow the files to be picked up via manual import or directory monitor.

**Comment by davidnewhall** [comment]
You can use the folder watcher feature for that purpose.

**Comment by 0xW1sKy** [comment]
It seems to be only looking for net new changes. Not torrents that have already completed.

Thanks,

Kyle Burk

Please excuse any spelling or grammar errors as this was sent from my iPhone.
________________________________

**Comment by davidnewhall** [comment]
> It seems to be only looking for net new changes. Not torrents that have already completed.

Correct. If you want to extract things that are already on disk with unpackerr, simply rename them and it will extract them.

>Also I dependent on how you're file watching it's likely not compatible with some file sharing tech.

Integrating with qbit wont solve this problem. 

Qbit doesn't store any information about extracted files like Starr apps, so it would require unpackerr remembering what it has already extracted. Your request is not trivial, and doesn't add much functionality beyond what's already available.

**Comment by 0xW1sKy** [comment]
Some of the limitations may be able to be overcome by integrating with something like flood (flood.js.org). This would also provide coverage for additional clients.

**Comment by austinwbest** [comment]
It is a sonarr limitation in this case. There is no automation with series packs and likely never will be. This also means manual intervention is required no matter what.

I would not expect an app that works with sonarr to do things sonarr doesn't even handle or support. The sonarr integration is just that, so it works as it should.

The alternative is a folder watcher which also does what is being asked of a manually grabbed item that isn't supported via api.

It is alot of work to go against the intended work flow to help users who grab things that are not even going to work (even if they where not packed as well).

Just my 2 cents anyways

**Comment by davidnewhall** [comment]
I didn't even catch the original statement about season packs. Now that I understand the problem you're trying to solve, I can safely say that it's really difficult to achieve that outcome. If Unpackerr integrated with qbit it's now going to extract everything qbit downloads, but then what logic? It gets complicated. Does it also check with the starr app to see if it's imported so it can delete it? That logic wont work with season packs since they never get imported. What if it extracted a game or app? I suppose you don't want that deleted after extraction. Do you just turn off clean-up entirely? In which can you can run `find | unrar` in `cron` and get the same result. 

There's nothing unpackerr can do that will make sonarr import a season pack.

**Comment by davidnewhall** [comment]
Is a qbit integration still something you'd use even though it can't solve the problem of sonarr importing season packs?

**Comment by 0xW1sKy** [comment]
i'm using the folder watcher currently and its working well.
