### ISSUE TITLE
Missing configuration info regarding SABnzbd

### ISSUE THREAD

**Issue by TagWolf** [Unpackerr/unpackerr#285]
I am assuming for sabnzbd that you want to set the following flags:

enable_unrar ( off )
enable_unzip ( off )
enable_7zip ( off )
enable_filejoin ( on ) <- Unsure
enable_tsjoin ( on ) <- Unsure

Can you add something to the readme for how this might co-exist with sabnzbd as this is a very common use case with Sonarr and Radarr, etc?

**Comment by davidnewhall** [comment]
I can't because I've never used, but someone else can. I'm happy to approve any useful additions.

**Comment by davidnewhall** [comment]
The wiki is also open to outside collaborators. You could certainly throw together a sab page where anyone can easily contribute.

**Comment by davidnewhall** [comment]
Since this issue was opened, the wiki has been disabled and readme reduced to a few paragraphs. All the documentation has been migrated to https://unpackerr.zip - the website/docs can be edited (contributions still welcome) in this repo: https://github.com/Unpackerr/unpackerr.github.io

I'm happy to clean up anything someone spends time on and submits.

**Comment by ThinkSalat** [comment]
In the categories tab, there's a processing option - this is what causes sab to unpack the files instead of unpackerr. Try to select an option that isn't default or +unpack.

**Comment by davidnewhall** [comment]
Thank you @ThinkSalat I added your notes to a new page here https://unpackerr.zip/docs/downloaders/usenet/

We can update it as more information makes sense. If someone else wants to put some time into it or make screenshots, let me know!
