### ISSUE TITLE
screen doesn't start when running the command

### ISSUE THREAD

**Issue by modulareverything** [Unpackerr/unpackerr#452]
I followed the Linux Seedbox instructions to the letter but when I run the screen command

```bash
screen -dmS unpackerr $HOME/unpackerr/unpackerr -c $HOME/unpackerr/unpackerr.conf
```

I get no errors but running `screen -ls` or `screen -r` nothing seems to be running.

I've checked that the directory is correct so I'm just looking for a little guidance. What could I check to see what might be going wrong?

Thanks

**Comment by davidnewhall** [comment]
What happens when you run the command? is `$HOME` set? is unpackerr @ `$HOME/unpackerr/unpackerr`?
`ls $HOME/unpackerr/unpackerr`

**Comment by davidnewhall** [comment]
![Screenshot 2024-07-11 at 11 32 31 AM](https://github.com/Unpackerr/unpackerr/assets/2402929/a3ff192a-fe02-46b1-9f29-bf7b502e985d)

**Comment by modulareverything** [comment]
Hey David, hopefully this provides a little more insight

![Screenshot 2024-07-12 at 9 24 33 am](https://github.com/user-attachments/assets/726fc2f9-da52-402e-a650-e0efffa59846)

**Comment by davidnewhall** [comment]
Looks like you cloned the repo. I'm not real sure why. The directions you should follow are found [here](https://unpackerr.zip/docs/install/seedbox). In the meantime you should delete that unpackerr repo clone.

**Comment by davidnewhall** [comment]
I [updated](https://github.com/Unpackerr/unpackerr.github.io/commit/77b1511a07dc9f811b84aac8e40053930eb73a11) the seedbox directions on the website slightly.

I changed the link to here: https://github.com/Unpackerr/unpackerr/releases/latest
Instead of here: https://github.com/Unpackerr/unpackerr/releases

This change in the link means you no longer have to click `Show all 23 assets` to see all the files. I also added a hint to which file you should download.

Please have a look and let me know if this helps.

**Comment by modulareverything** [comment]
Thanks, David, no idea how I'd done that, I must have been half asleep so sorry for asking the stupid question but thanks for correcting me. That's solved the problem 😄
